// src/lib/components/cards/BlogPost.vue
<script lang="ts">
import { parseDateStr } from "../../parseDateStr"

const p = defineProps<{
  title: string
  description?: string
  date: string
  slug: string
}>()

const { readableDate, isoDate } = parseDateStr(p.date)

const _parsedSlug = `/blog/${p.slug}`
</script>

<template>
  <div id="post-item" class="flex flex-col gap-y-2">
    <a :href="_parsedSlug">
      <slot />
    </a>
    <h2 class="text-[1.75rem] leading-tight font-bold pt-2">
      <a :href="_parsedSlug">{{ title }}</a>
    </h2>
    <p v-show="description" class="overflow-hidden line-clamp-3 opacity-75 leading-relaxed">
      {{ description }}
    </p>
    <time :datetime="isoDate" class="text-sm">{{ readableDate }}</time>
  </div>
</template>

// src/components/cards/BlogPost.svelte
<script lang="ts">
  import { parseDateStr } from "../../utils"

  export let title: string
  export let description: string = ""
  export let date: string
  export let image: string

  const { readableDate, isoDate } = parseDateStr(date)
</script>

<div id="blog-post">
  <img class="rounded-md overflow-hidden aspect-video" src={image} alt={`Banner for ${title}`} />
  <h2 class="text-3xl font-bold py-1.5">{title}</h2>
  {#if description}
    <p>{description}</p>
  {/if}
  <time datetime={isoDate}>{readableDate}</time>
</div>
